# Generated by Django 5.2.7 on 2025-10-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educatorarea',
            name='area',
        ),
        migrations.RemoveField(
            model_name='callrequest',
            name='educator',
        ),
        migrations.RemoveField(
            model_name='callrequest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='educatordegree',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='educatorlicense',
            name='educator',
        ),
        migrations.RemoveField(
            model_name='educatordegree',
            name='educator',
        ),
        migrations.RemoveField(
            model_name='educatorarea',
            name='educator',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='CallRequest',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
        migrations.DeleteModel(
            name='EducatorLicense',
        ),
        migrations.DeleteModel(
            name='EducatorDegree',
        ),
        migrations.DeleteModel(
            name='Educator',
        ),
        migrations.DeleteModel(
            name='EducatorArea',
        ),
    ]
