# Generated by Django 5.2.7 on 2025-10-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='callrequest',
            table='call_requests',
        ),
    ]
