# Generated by Django 5.2.7 on 2025-10-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
