# Generated by Django 5.2.7 on 2025-10-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degree', '0002_alter_degree_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='degree',
            table='degree',
        ),
    ]
