# Generated by Django 5.2.7 on 2025-10-06 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('degree', '0001_initial'),
        ('educators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educatorarea',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.area'),
        ),
        migrations.AlterField(
            model_name='educatordegree',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='degree.degree'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
    ]
