# Generated by Django 5.2.7 on 2025-10-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educators', '0002_alter_educatorarea_area_alter_educatordegree_degree_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='educator',
            table='educator',
        ),
        migrations.AlterModelTable(
            name='educatorarea',
            table='educator_area',
        ),
        migrations.AlterModelTable(
            name='educatordegree',
            table='educator_degree',
        ),
        migrations.AlterModelTable(
            name='educatorlicense',
            table='educator_license',
        ),
    ]
